USE [editora]
GO

BEGIN TRANSACTION;

CREATE TABLE [dbo].[livro_x_autor]
(
	[id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[id_autor] BIGINT NOT NULL,
	[id_livro] BIGINT NOT NULL
)
GO

COMMIT TRANSACTION;

BEGIN TRANSACTION;

	ALTER TABLE [dbo].[livro_x_autor] WITH CHECK
		ADD CONSTRAINT [FK_autor] FOREIGN KEY ([id_autor]) REFERENCES [dbo].[autor] ([id])
		ON DELETE CASCADE
		ON UPDATE CASCADE
	GO

COMMIT TRANSACTION;

BEGIN TRANSACTION;

	ALTER TABLE [dbo].[livro_x_autor] WITH CHECK
		ADD CONSTRAINT [FK_livro] FOREIGN KEY ([id_livro]) REFERENCES [dbo].[livro] ([id])
		ON DELETE CASCADE
		ON UPDATE CASCADE
	GO
		
COMMIT TRANSACTION;
