USE [editora]
GO

BEGIN TRANSACTION;

CREATE TABLE [dbo].[livro]
(
	[id] BIGINT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	[titulo] NVARCHAR(100) NOT NULL,
	[ISBN] NVARCHAR(13) NOT NULL,
	[ano_lancamento] INT NOT NULL
)
GO

COMMIT TRANSACTION;
