USE [editora]
GO

BEGIN TRANSACTION;

CREATE TABLE [dbo].[usuario]
(
	id BIGINT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	nome NVARCHAR(100) NOT NULL,
	email NVARCHAR(50) UNIQUE NOT NULL,
	senha VARBINARY(256) NOT NULL
);
GO

COMMIT TRANSACTION;
